# eb-config.yml
branch-defaults:
  default:
    environment: eb-banking-env
    group_suffix: null
global:
  application_name: eb-banking-app
  default_ec2_keyname: LuisMorenoWorkloads
  default_platform: python-3.9
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application